name: Deploy Piter to Contabo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (metadata only)
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then echo "ERROR: DEPLOY_HOST secret is missing"; exit 1; fi
          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then echo "ERROR: DEPLOY_USER secret is missing"; exit 1; fi
          if [ -z "${{ secrets.DEPLOY_SSH_KEY }}" ]; then echo "ERROR: DEPLOY_SSH_KEY secret is missing"; exit 1; fi

      - name: Ping host
        run: |
          echo "Pinging ${{ secrets.DEPLOY_HOST }} ..."
          if ! ping -c 3 -W 3 "${{ secrets.DEPLOY_HOST }}"; then
            echo "ERROR: Ping to ${{ secrets.DEPLOY_HOST }} failed. Check DEPLOY_HOST (use the server IP, not a proxied hostname).";
            exit 1;
          fi

      - name: SSH ping (debug)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          timeout: 90s
          command_timeout: 15m
          debug: true
          script_stop: true
          script: |
            echo "SSH OK on $(hostname)"

      - name: Remote deploy Piter
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          timeout: 5m
          command_timeout: 30m
          debug: true
          script_stop: true
          script: |
            set -e
            echo "--- Ensuring clean deploy by removing old directory ---"
            rm -rf /home/piter/piter-app
            
            echo "--- Cloning fresh repository ---"
            git clone --branch main git@github.com:drower22/piter-python-contabo.git /home/piter/piter-app
            cd /home/piter/piter-app
            if [ ! -d .venv ]; then
              python3 -m venv .venv
            fi
            source .venv/bin/activate
            python -m pip install -U pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            elif [ -f backend/requirements.txt ]; then
              pip install -r backend/requirements.txt
            fi
            deactivate
            sudo systemctl restart piter-api
            sudo systemctl reload nginx || true
            systemctl status piter-api --no-pager -n 10 || true
